# Generated by Django 4.2.7 on 2024-08-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_pelanggaran_alter_chatid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wilayah',
            options={'verbose_name_plural': 'Daftar Wilayah Yayasan Nurul Afifah'},
        ),
        migrations.RenameField(
            model_name='pelanggaran',
            old_name='subject',
            new_name='tindakan',
        ),
    ]
